### ISSUE TITLE
Found datasets that render diagram incorrectly

### ISSUE THREAD

**Issue by tamu-sad-iii** [s-u/venneuler#1]
```

A 70.0
B 100.0
C 25.5
D 2.0
E 3.0
"A&B" 10
```

![image](https://github.com/s-u/venneuler/assets/144841721/e165f548-f805-4fd8-93e7-7d2fea385339)

```

A 70.0
B 100.0
C 25.5
D 2.0
E 3.0
F 10.0  
"A&B" 10
"A&C" 10
"D&A" 0
"D&B" 0
"D&C" 0
"D&E" 0
"E&A" 0
"E&B" 0
"E&C" 0
"E&D" 0
```
![image](https://github.com/s-u/venneuler/assets/144841721/c3ad1b83-94c9-4db2-a4e8-feb3c794b8d1)

**Comment by s-u** [comment]
Please see the documentation about residuals (always look at the stress and residuals first) and [the algorithm](https://www.cs.uic.edu/~wilkinson/Publications/venneuler.pdf). The solution is an approximation and if you have many sets with no intersection they should not be included because it affects the SVD step and there is no point in adding them - you get what you expect if you remove the empty sets which have no bearing on the solution:

```
plot(venneuler(c(A=70.0, B=100.0, "A&B"=10)))
```
![image](https://github.com/s-u/venneuler/assets/2073427/54903f02-8b1f-411e-9b76-6dda175a8f20)

```
plot(venneuler(c(A=70.0, B=100.0, C=25.5, "A&B"=10, "A&C"=10)))
```
![image](https://github.com/s-u/venneuler/assets/2073427/85011b57-2537-462d-bf0b-a1145204975a)
